name: CI - Feature Branches

on:
  push:
    branches: [ 'feature/**' ]
  pull_request:
    branches: [ 'feature/**', 'develop' ]

jobs:
  redos-build:
    uses: ./.github/workflows/jobs/redos-build.yaml

  altlinux-latest-build:
    uses: ./.github/workflows/jobs/altlinux-latest-build.yaml

  altlinux-10-build:
    uses: ./.github/workflows/jobs/altlinux-10-build.yaml

  windows-build:
    uses: ./.github/workflows/jobs/windows-build.yaml

  feature-branch-report:
    uses: ./.github/workflows/reports/feature-report.yaml