name: CI - Main Platforms

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  redos-production:
    uses: ./.github/workflows/jobs/redos-build.yaml
    with:
      build-type: Release
      create-artifact: true

  altlinux-latest-production:
    uses: ./.github/workflows/jobs/altlinux-latest-build.yaml
    with:
      build-type: Release
      create-artifact: true

  altlinux-10-production:
    uses: ./.github/workflows/jobs/altlinux-10-build.yaml
    with:
      build-type: Release
      create-artifact: true

  windows-production:
    uses: ./.github/workflows/jobs/windows-build.yaml
    with:
      build-type: Release
      create-artifact: true

  compatibility-report:
    uses: ./.github/workflows/reports/production-report.yaml